%% plot_ellipsoid.m
%
% Description:
%   This function plots an ellipsoid in the configuration specified by Twb,
%   a 4x4 homogeneous transformation matrix, i.e., an element of SE(3).
%   This function expands on MATLAB's built-in ellipsoid() function and
%   uses the 3x3 rotation matrix Rwb = Twb(1:3,1:3) to rotate the ellipsoid
%   rather than using MATLAB's built-in rotate() function, which rotates by
%   a specific angle about a specific axis.
%
% Inputs:
%   ax: a handle to the axes on which to plot the ellipsoid
%   Twb: configuration of the ellipsoid's CoM frame {b} relative to the
%        world frame {w}, represented as a 4x4 homogeneous transformation
%        matrix, i.e., an element of SE(3).
%   body_params: a struct with many fields, including geometry parameters,
%                generated by calling create_body().
%
% Outputs:
%   none

function plot_ellipsoid(ax,Twb,body_params)
    % generate [Xb,Yb,Zb] coordinates of ellipsoid vertices in body frame:
    [Xb,Yb,Zb] = ellipsoid(0,0,0,...
                           body_params.geom.semi_axes.x,...
                           body_params.geom.semi_axes.y,...
                           body_params.geom.semi_axes.z,...
                           body_params.viz.face.num);
                       
    % create homogeneous representation of body-frame vertex coordinates
    % with dimensions 4-by(n+1)^2, where n is the number of faces:
    n = body_params.viz.face.num;
    Cb_homog = reshape(cat(1,reshape(Xb,[1,n+1,n+1]),...
                             reshape(Yb,[1,n+1,n+1]),...
                             reshape(Zb,[1,n+1,n+1]),...
                             reshape(ones(n+1),[1,n+1,n+1])),[4,(n+1)^2]);
    
                    
    % use Twb to transform body-frame vertex coordinates to world-frame
    % vertex coordinates:
    Cw_homog = reshape(Twb*Cb_homog,[4,n+1,n+1]);
    Xw = squeeze(Cw_homog(1,:,:));
    Yw = squeeze(Cw_homog(2,:,:));
    Zw = squeeze(Cw_homog(3,:,:));
    
    % visualize
    surf(ax,Xw,Yw,Zw,...
        'FaceColor',body_params.viz.face.color,...
        'FaceAlpha',body_params.viz.face.alpha,...
        'EdgeColor',body_params.viz.edge.color,...
        'EdgeAlpha',body_params.viz.edge.alpha);
    
end