%% plot_rect_prism.m
%
% Description:
%   This function plots a rectangular prism in the configuration specified by Twb,
%   a 4x4 homogeneous transformation matrix, i.e., an element of SE(3).
%
% Inputs:
%   ax: a handle to the axes on which to plot the rectangular prism
%   Twb: configuration of the prism's CoM frame {b} relative to the
%        world frame {w}, represented as a 4x4 homogeneous transformation
%        matrix, i.e., an element of SE(3).
%   body_params: a struct with many fields, including geometry parameters,
%                generated by calling create_body().
%
% Outputs:
%   none

function plot_rect_prism(ax,Twb,body_params)
% transform (rotate and translate) each point in the body's
% triangulation:
default_TR = body_params.geom.TR;
points = [default_TR.Points,ones(size(default_TR.Points,1),1)]...
       * transpose(Twb)*[eye(3);zeros(1,3)];

% reconnect the transformed points according to the original triangulation:
TR = triangulation(default_TR.ConnectivityList,points);

% plot the new triangulation object:
trisurf(TR,'FaceColor',body_params.viz.face.color,...
           'FaceAlpha',body_params.viz.face.alpha,...
           'EdgeColor',body_params.viz.edge.color,...
           'EdgeAlpha',body_params.viz.edge.alpha,...
           'Parent',ax);

end